from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
fsl_flexspi_nor_boot.c
flexspi_nor_config.c
""")

CPPPATH = [cwd]
CPPDEFINES = []

group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
