/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#include "dcd.h"

/* Component ID definition, used by tools. */
#ifndef FSL_COMPONENT_ID
#define FSL_COMPONENT_ID "platform.drivers.xip_board"
#endif

#if defined(XIP_BOOT_HEADER_ENABLE) && (XIP_BOOT_HEADER_ENABLE == 1)
#if defined(XIP_BOOT_HEADER_DCD_ENABLE) && (XIP_BOOT_HEADER_DCD_ENABLE == 1)
#if defined(__CC_ARM) || defined(__ARMCC_VERSION) || defined(__GNUC__)
__attribute__((section(".boot_hdr.dcd_data"), used))
#elif defined(__ICCARM__)
#pragma location = ".boot_hdr.dcd_data"
#endif

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: DCDx v3.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 10.0.0
output_format: c_array
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* COMMENTS BELOW ARE USED AS SETTINGS FOR DCD DATA */
const uint8_t dcd_data[] = {
	/* HEADER */
	/* Tag */
	0xD2,
	/* Image Length */
	0x00, 0xD0,
	/* Version */
	0x41,

	/* COMMANDS */

	/* group: 'clk', comment: '配置时钟和时钟树配置一致(不是全部)配置SEMC：159.4Hzh' */
	/* #1, command: write_clear_and_set_bits, address: CCM_ANALOG_PFD_528, value: set:0x800000, clr:0x0, size: 4, comment: '关闭Pfd2输出 SYS_PLL' */
	/* clear_bits command */
	0xCC, 0x00, 0x0C, 0x0C, 0x40, 0x0D, 0x81, 0x00, 0x00, 0x00, 0x00, 0x00,
	/* set_bits command */
	0xCC, 0x00, 0x0C, 0x1C, 0x40, 0x0D, 0x81, 0x00, 0x00, 0x80, 0x00, 0x00,
	/* #2, command: write_clear_and_set_bits, address: CCM_ANALOG_PFD_528, value: set:0xc0000, clr:0xb30000, size: 4, comment: '设置PFD2_FRAC为12并打开输出' */
	/* clear_bits command */
	0xCC, 0x00, 0x0C, 0x0C, 0x40, 0x0D, 0x81, 0x00, 0x00, 0xB3, 0x00, 0x00,
	/* set_bits command */
	0xCC, 0x00, 0x0C, 0x1C, 0x40, 0x0D, 0x81, 0x00, 0x00, 0x0C, 0x00, 0x00,
	/* #3.1-2, command header bytes for merged 'Write - clear bits' command */
	0xCC, 0x00, 0x14, 0x0C,
	/* #3.1, command: write_clear_bits, address: CCM_CCGR3, value: 0x30, size: 4, comment: 'Disable Semc clock gate.' */
	0x40, 0x0F, 0xC0, 0x74, 0x00, 0x00, 0x00, 0x30,
	/* #3.2, command: write_clear_bits, address: CCM_CCGR1, value: 0xC0000, size: 4, comment: 'Disable Semc exsc  clock gate.' */
	0x40, 0x0F, 0xC0, 0x6C, 0x00, 0x0C, 0x00, 0x00,
	/* #4, command: write_clear_and_set_bits, address: CCM_CBCDR, value: set:0x40000, clr:0x30000, size: 4, comment: 'Set SEMC_PODF. 5分频' */
	/* clear_bits command */
	0xCC, 0x00, 0x0C, 0x0C, 0x40, 0x0F, 0xC0, 0x14, 0x00, 0x03, 0x00, 0x00,
	/* set_bits command */
	0xCC, 0x00, 0x0C, 0x1C, 0x40, 0x0F, 0xC0, 0x14, 0x00, 0x04, 0x00, 0x00,
	/* #5, command: check_any_bit_clear, address: CCM_CDHIPR, value: 0x1, size: 4, comment: '等候 semc_podf 分频器不忙' */
	0xCF, 0x00, 0x0C, 0x0C, 0x40, 0x0F, 0xC0, 0x48, 0x00, 0x00, 0x00, 0x01,
	/* #6, command: write_clear_and_set_bits, address: CCM_CBCDR, value: set:0x0, clr:0x80, size: 4, comment: 'Set Semc alt clock source.选择PPL2_PFD2_CLK' */
	/* clear_bits command */
	0xCC, 0x00, 0x0C, 0x0C, 0x40, 0x0F, 0xC0, 0x14, 0x00, 0x00, 0x00, 0x80,
	/* set_bits command */
	0xCC, 0x00, 0x0C, 0x1C, 0x40, 0x0F, 0xC0, 0x14, 0x00, 0x00, 0x00, 0x00,
	/* #7, command: write_clear_and_set_bits, address: CCM_CBCDR, value: set:0x40, clr:0x0, size: 4, comment: 'Set Semc clock source.选择SEMC_CLK_SEL' */
	/* clear_bits command */
	0xCC, 0x00, 0x0C, 0x0C, 0x40, 0x0F, 0xC0, 0x14, 0x00, 0x00, 0x00, 0x00,
	/* set_bits command */
	0xCC, 0x00, 0x0C, 0x1C, 0x40, 0x0F, 0xC0, 0x14, 0x00, 0x00, 0x00, 0x40,
	/* #8.1-6, command header bytes for merged 'Write - set bits' command */
	0xCC, 0x00, 0x34, 0x1C,
	/* #8.1, command: write_set_bits, address: CCM_CCGR3, value: 0x30, size: 4, comment: '打开Semc clock gate.132MHz' */
	0x40, 0x0F, 0xC0, 0x74, 0x00, 0x00, 0x00, 0x30,
	/* #8.2, command: write_set_bits, address: CCM_CCGR1, value: 0xC0000, size: 4, comment: '打开Semc exsc clock gate.132MHz' */
	0x40, 0x0F, 0xC0, 0x6C, 0x00, 0x0C, 0x00, 0x00,
	/* #8.3, command: write_set_bits, address: CCM_CCGR1, value: 0xC000000, size: 4, comment: '打开GPIO1exsc clock ' */
	0x40, 0x0F, 0xC0, 0x6C, 0x0C, 0x00, 0x00, 0x00,
	/* #8.4, command: write_set_bits, address: CCM_CCGR0, value: 0xC0000000, size: 4, comment: '打开GPIO2exsc clock ' */
	0x40, 0x0F, 0xC0, 0x68, 0xC0, 0x00, 0x00, 0x00,
	/* #8.5, command: write_set_bits, address: CCM_CCGR2, value: 0xC000000, size: 4, comment: '打开GPIO3exsc clock ' */
	0x40, 0x0F, 0xC0, 0x70, 0x0C, 0x00, 0x00, 0x00,
	/* #8.6, command: write_set_bits, address: CCM_CCGR1, value: 0xC0000000, size: 4, comment: '打开GPIO5exsc clock ' */
	0x40, 0x0F, 0xC0, 0x6C, 0xC0, 0x00, 0x00, 0x00
	};
/* BE CAREFUL MODIFYING THIS SETTINGS - IT IS YAML SETTINGS FOR TOOLS */

#else
const uint8_t dcd_data[] = {0x00};
#endif /* XIP_BOOT_HEADER_DCD_ENABLE */
#endif /* XIP_BOOT_HEADER_ENABLE */
